/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

import Clases.Validador;

/**
 *
 * @author Brandon Emmanuel Reséndiz Granados, Ruben Lora Cruz, Alejandro Avila Rangel
 * 
 */
public class ProductoGUI extends javax.swing.JPanel {

        /**
         * Creates new form ProductoGUI
         */

        private Validador _validador = new Validador();

        public ProductoGUI() {
                _validador = new Validador();
                initComponents();

                btnGuardar.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                                validarCampos();
                        }
                });

        }

        public void limpiarCampos() {
                txtNombre.setText("");
                txtCategoria.setText("");
                txtPrecio.setText("");
                txtStock.setText("");
        }

        private void validarCampos() {
                boolean camposValidos = true;

                if (!_validador.validarCampoVacio(txtNombre, "Nombre")) {
                        camposValidos = false;
                }

                if (!_validador.validarCampoVacio(txtCategoria, "Categoria")) {
                        camposValidos = false;
                }

                if (!_validador.validarCampoVacio(txtPrecio, "Precio")) {
                        camposValidos = false;
                } else if (!txtPrecio.getText().matches("^\\d+(\\.\\d{1,2})?$")) {
                        JOptionPane.showMessageDialog(null, "El precio debe ser un número con dos decimales.", "Error",
                                        JOptionPane.ERROR_MESSAGE);
                        camposValidos = false;
                } else if (Double.parseDouble(txtPrecio.getText()) <= 0) {
                        JOptionPane.showMessageDialog(null, "El precio debe ser mayor que cero.", "Error",
                                        JOptionPane.ERROR_MESSAGE);
                        camposValidos = false;
                }

                if (!_validador.validarCampoVacio(txtStock, "Stock")) {
                        camposValidos = false;
                } else if (!txtStock.getText().matches("^\\d+$")) {
                        JOptionPane.showMessageDialog(null, "El stock debe ser un número entero.", "Error",
                                        JOptionPane.ERROR_MESSAGE);
                        camposValidos = false;
                } else if (Integer.parseInt(txtStock.getText()) <= 0) {
                        JOptionPane.showMessageDialog(null, "El stock debe ser mayor que cero.", "Error",
                                        JOptionPane.ERROR_MESSAGE);
                        camposValidos = false;
                }
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                txtNombre = new javax.swing.JTextField();
                lblNombre = new javax.swing.JLabel();
                lblPrecio = new javax.swing.JLabel();
                txtPrecio = new javax.swing.JTextField();
                lblStock = new javax.swing.JLabel();
                txtStock = new javax.swing.JTextField();
                lblCategoria = new javax.swing.JLabel();
                txtCategoria = new javax.swing.JTextField();
                btnGuardar = new javax.swing.JButton();
                lblTituloProducto = new javax.swing.JLabel();

                txtNombre.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtNombreActionPerformed(evt);
                        }
                });

                lblNombre.setText("Nombre");

                lblPrecio.setText("Precio");

                lblStock.setText("Stock");

                lblCategoria.setText("Categoria");

                btnGuardar.setText("Guardar");

                lblTituloProducto.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
                lblTituloProducto.setText("Producto");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(215, 215, 215)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(lblCategoria)
                                                                                                                .addComponent(lblNombre)
                                                                                                                .addComponent(lblPrecio)
                                                                                                                .addComponent(lblStock))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                false)
                                                                                                                .addComponent(txtNombre)
                                                                                                                .addComponent(txtPrecio)
                                                                                                                .addComponent(txtStock)
                                                                                                                .addComponent(txtCategoria,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                126,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(272, 272, 272)
                                                                                                .addComponent(btnGuardar))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(245, 245, 245)
                                                                                                .addComponent(lblTituloProducto)))
                                                                .addContainerGap(260, Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addGap(51, 51, 51)
                                                                .addComponent(lblTituloProducto)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                45,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(lblNombre)
                                                                                .addComponent(txtNombre,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addGap(18, 18, 18)
                                                                                                                .addGroup(layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                .addComponent(lblPrecio)
                                                                                                                                .addComponent(txtPrecio,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(lblCategoria))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(64, 64, 64)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(txtStock,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(lblStock))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(txtCategoria,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(39, 39, 39)
                                                                .addComponent(btnGuardar)
                                                                .addGap(46, 46, 46)));
        }// </editor-fold>//GEN-END:initComponents

        public static void main(String[] args) {
                SwingUtilities.invokeLater(new Runnable() {
                        @Override
                        public void run() {
                                JFrame frame = new JFrame("Agrega Producto");
                                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                                frame.setSize(600, 400);

                                ProductoGUI productoPanel = new ProductoGUI();
                                frame.add(productoPanel);

                                frame.setVisible(true);
                        }
                });
        }

        private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtNombreActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_txtNombreActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnGuardar;
        private javax.swing.JLabel lblCategoria;
        private javax.swing.JLabel lblNombre;
        private javax.swing.JLabel lblPrecio;
        private javax.swing.JLabel lblStock;
        private javax.swing.JLabel lblTituloProducto;
        private javax.swing.JTextField txtCategoria;
        private javax.swing.JTextField txtNombre;
        private javax.swing.JTextField txtPrecio;
        private javax.swing.JTextField txtStock;
        // End of variables declaration//GEN-END:variables
}
